// THIS FILE IS AUTO-GENERATED by scripts/sync-fifa-teams.mjs

export type Team = {
  code: string;
  name: string;
  rank: number;
  group: string;
};

export const TEAMS: Team[] = [
  { code: "esp", name: "Spain", rank: 1, group: "H" },
  { code: "arg", name: "Argentina", rank: 2, group: "J" },
  { code: "fra", name: "France", rank: 3, group: "I" },
  { code: "eng", name: "England", rank: 4, group: "L" },
  { code: "bra", name: "Brazil", rank: 5, group: "C" },
  { code: "por", name: "Portugal", rank: 6, group: "K" },
  { code: "ned", name: "Netherlands", rank: 7, group: "F" },
  { code: "mar", name: "Morocco", rank: 8, group: "C" },
  { code: "bel", name: "Belgium", rank: 9, group: "G" },
  { code: "ger", name: "Germany", rank: 10, group: "E" },
  { code: "cro", name: "Croatia", rank: 11, group: "L" },
  { code: "sen", name: "Senegal", rank: 12, group: "I" },
  { code: "col", name: "Colombia", rank: 14, group: "K" },
  { code: "usa", name: "USA", rank: 15, group: "D" },
  { code: "mex", name: "Mexico", rank: 16, group: "A" },
  { code: "uru", name: "Uruguay", rank: 17, group: "H" },
  { code: "sui", name: "Switzerland", rank: 18, group: "B" },
  { code: "jpn", name: "Japan", rank: 19, group: "F" },
  { code: "irn", name: "IR Iran", rank: 20, group: "G" },
  { code: "kor", name: "Korea Republic", rank: 22, group: "A" },
  { code: "ecu", name: "Ecuador", rank: 23, group: "E" },
  { code: "aut", name: "Austria", rank: 24, group: "J" },
  { code: "aus", name: "Australia", rank: 27, group: "D" },
  { code: "alg", name: "Algeria", rank: 28, group: "J" },
  { code: "can", name: "Canada", rank: 29, group: "B" },
  { code: "egy", name: "Egypt", rank: 31, group: "G" },
  { code: "nor", name: "Norway", rank: 32, group: "I" },
  { code: "pan", name: "Panama", rank: 33, group: "L" },
  { code: "civ", name: "Côte d'Ivoire", rank: 37, group: "E" },
  { code: "sco", name: "Scotland", rank: 38, group: "C" },
  { code: "par", name: "Paraguay", rank: 40, group: "D" },
  { code: "tun", name: "Tunisia", rank: 47, group: "F" },
  { code: "uzb", name: "Uzbekistan", rank: 52, group: "K" },
  { code: "qat", name: "Qatar", rank: 56, group: "B" },
  { code: "rsa", name: "South Africa", rank: 60, group: "A" },
  { code: "ksa", name: "Saudi Arabia", rank: 61, group: "H" },
  { code: "jor", name: "Jordan", rank: 64, group: "J" },
  { code: "cpv", name: "Cabo Verde", rank: 67, group: "H" },
  { code: "gha", name: "Ghana", rank: 72, group: "L" },
  { code: "cuw", name: "Curaçao", rank: 81, group: "E" },
  { code: "hai", name: "Haiti", rank: 83, group: "C" },
  { code: "nzl", name: "New Zealand", rank: 85, group: "G" },
];
